version: 0.1
component: build
timeoutInSeconds: 20000
runAs: root
shell: bash
env:
  variables:
    "githubSourcePath": "${OCI_WORKSPACE_DIR}/TestBuildSource_GitHub"
    "gitlabSourcePath": "${OCI_WORKSPACE_DIR}/TestBuildSource_GitLab"
    "bitbucketCloudSourcePath": "${OCI_WORKSPACE_DIR}/TestBuildSource_BitbucketCloud"
    "bitbucketServerSourcePath": "${OCI_WORKSPACE_DIR}/TestBuildSource_BitbucketServer"
    "publicGitlabServerSourcePath": "${OCI_WORKSPACE_DIR}/TestBuildSource_PublicGitlabServer"
    "vbsSourcePath": "${OCI_WORKSPACE_DIR}/TestBuildSource_Vbs"
    "zipFilesDirectoryPath": "${OCI_WORKSPACE_DIR}/zipFiles"
  exportedVariables:
   - GITHUB_MD5_HASH
   - GITLAB_MD5_HASH
   - BITBUCKET_CLOUD_MD5_HASH
   - BITBUCKET_SERVER_MD5_HASH
   - PUBLIC_GITLAB_SERVER_MD5_HASH
   - VBS_MD5_HASH
steps:
  - type: Command
    name: "GitHub repo checksum"
    command: |
      mkdir zipFiles && zip -r github.zip TestBuildSource_GitHub && md5sum github.zip
  - type: Command
    name: "Create directory for storing zip files"
    command: |
      mkdir ${zipFilesDirectoryPath}
  - type: Command
    name: "Calculating MD5 Hash of Github Large Repo"
    command: |
      zip -r ${zipFilesDirectoryPath}/github.zip ${githubSourcePath}
      export GITHUB_MD5_HASH=`md5sum ${zipFilesDirectoryPath}/github.zip | awk '{ print $1 }'`
    onFailure:
      - type: Command
        command: |
          echo "Calculating MD5 Hash of Github Large Repo failed :("
  - type: Command
    name: "Calculating MD5 Hash of Gitlab Large Repo"
    command: |
      zip -r ${zipFilesDirectoryPath}/gitlab.zip ${OCI_WORKSPACE_DIR}/${gitlabSourcePath}
      export GITLAB_MD5_HASH=`md5sum ${zipFilesDirectoryPath}/gitlab.zip | awk '{ print $1 }'`
    onFailure:
      - type: Command
        command: |
          echo "Calculating MD5 Hash of Gitlab Large Repo failed :("
  - type: Command
    name: "Calculating MD5 Hash of Bitbucket Cloud Large Repo"
    command: |
      zip -r ${zipFilesDirectoryPath}/bitbucketCloud.zip ${OCI_WORKSPACE_DIR}/${bitbucketCloudSourcePath}
      export BITBUCKET_CLOUD_MD5_HASH=`md5sum ${zipFilesDirectoryPath}/bitbucketCloud.zip | awk '{ print $1 }'`
    onFailure:
      - type: Command
        command: |
          echo "Calculating MD5 Hash of Bitbucket Cloud Large Repo failed :("
  - type: Command
    name: "Calculating MD5 Hash of Bitbucket Server Large Repo"
    command: |
      zip -r ${zipFilesDirectoryPath}/bitbucketServer.zip ${OCI_WORKSPACE_DIR}/${bitbucketServerSourcePath}
      export BITBUCKET_SERVER_MD5_HASH=`md5sum ${zipFilesDirectoryPath}/bitbucketServer.zip | awk '{ print $1 }'`
    onFailure:
      - type: Command
        command: |
          echo "Calculating MD5 Hash of Bitbucket Server Large Repo failed :("
  - type: Command
    name: "Calculating MD5 Hash of Public Gitlab Server Large Repo"
    command: |
      zip -r ${zipFilesDirectoryPath}/publicGitlabServer.zip ${OCI_WORKSPACE_DIR}/${publicGitlabServerSourcePath}
      export PUBLIC_GITLAB_SERVER_MD5_HASH=`md5sum ${zipFilesDirectoryPath}/publicGitlabServer.zip | awk '{ print $1 }'`
    onFailure:
      - type: Command
        command: |
          echo "Calculating MD5 Hash of Public Gitlab Server Large Repo failed :("
  - type: Command
    name: "Calculating MD5 Hash of VBS Large Repo"
    command: |
      zip -r ${zipFilesDirectoryPath}/vbs.zip ${OCI_WORKSPACE_DIR}/${vbsSourcePath}
      export VBS_MD5_HASH=`md5sum ${zipFilesDirectoryPath}/vbs.zip | awk '{ print $1 }'`
    onFailure:
      - type: Command
        command: |
          echo "Calculating MD5 Hash of VBS Large Repo failed :("
  - type: Command
    name: "Deleting all the zip files"
    command: |
      rm -r ${zipFilesDirectoryPath}
#  - type: Command
#    name: "Building spark (Github Large Repo) in local"
#    command: |
#      cd ${OCI_WORKSPACE_DIR}/${githubSource}
#      chmod -R +x ./build/mvn
#      ./build/mvn -DskipTests clean package
#  - type: Command
#    name: "run the Pi example locally"
#    command: |
#      chmod -R +x .
#      ./bin/run-example SparkPi
