version: 0.1
component: build
timeoutInSeconds: 20000
runAs: root
shell: bash
env:
  exportedVariables:
   - GITHUB_MD5_HASH
   - GITLAB_MD5_HASH
   - BITBUCKET_CLOUD_MD5_HASH
   - BITBUCKET_SERVER_MD5_HASH
   - PUBLIC_GITLAB_SERVER_MD5_HASH
   - VBS_MD5_HASH
steps:
  - type: Command
    name: "Calculating MD5 Hash of Github Large Repo"
    command: |
      zip -d TestBuildSource_GitHub.zip TestBuildSource_GitHub/.git/*
      export GITHUB_MD5_HASH=`md5sum TestBuildSource_GitHub.zip | awk '{ print $1 }'`
      echo Github hash is $GITHUB_MD5_HASH
    onFailure:
      - type: Command
        command: |
          echo "Calculating MD5 Hash of Github Large Repo failed :("
  - type: Command
    name: "Calculating MD5 Hash of Gitlab Large Repo"
    command: |
      zip -d TestBuildSource_GitLab.zip TestBuildSource_GitLab/.git/*
      export GITLAB_MD5_HASH=`md5sum TestBuildSource_GitLab.zip | awk '{ print $1 }'`
      echo Gitlab hash is $GITLAB_MD5_HASH
    onFailure:
      - type: Command
        command: |
          echo "Calculating MD5 Hash of Gitlab Large Repo failed :("
  - type: Command
    name: "Calculating MD5 Hash of Bitbucket Cloud Large Repo"
    command: |
      zip -d TestBuildSource_BitbucketCloud.zip TestBuildSource_BitbucketCloud/.git/*
      export BITBUCKET_CLOUD_MD5_HASH=`md5sum TestBuildSource_BitbucketCloud.zip | awk '{ print $1 }'`
    onFailure:
      - type: Command
        command: |
          echo "Calculating MD5 Hash of Bitbucket Cloud Large Repo failed :("
  - type: Command
    name: "Calculating MD5 Hash of Bitbucket Server Large Repo"
    command: |
      zip -d TestBuildSource_BitbucketServer.zip TestBuildSource_BitbucketServer/.git/*
      export BITBUCKET_SERVER_MD5_HASH=`md5sum TestBuildSource_BitbucketServer.zip | awk '{ print $1 }'`
    onFailure:
      - type: Command
        command: |
          echo "Calculating MD5 Hash of Bitbucket Server Large Repo failed :("
  - type: Command
    name: "Calculating MD5 Hash of Public Gitlab Server Large Repo"
    command: |
      zip -d TestBuildSource_PublicGitlabServer.zip TestBuildSource_PublicGitlabServer/.git/*
      export PUBLIC_GITLAB_SERVER_MD5_HASH=`md5sum TestBuildSource_PublicGitlabServer.zip | awk '{ print $1 }'`
    onFailure:
      - type: Command
        command: |
          echo "Calculating MD5 Hash of Public Gitlab Server Large Repo failed :("
  - type: Command
    name: "Calculating MD5 Hash of VBS Large Repo"
    command: |
      zip -d TestBuildSource_Vbs.zip TestBuildSource_Vbs/.git/*
      export VBS_MD5_HASH=`md5sum TestBuildSource_Vbs.zip | awk '{ print $1 }'`
    onFailure:
      - type: Command
        command: |
          echo "Calculating MD5 Hash of VBS Large Repo failed :("
#  - type: Command
#    name: "Building spark (Github Large Repo) in local"
#    command: |
#      cd ${OCI_WORKSPACE_DIR}/${githubSource}
#      chmod -R +x ./build/mvn
#      ./build/mvn -DskipTests clean package
#  - type: Command
#    name: "run the Pi example locally"
#    command: |
#      chmod -R +x .
#      ./bin/run-example SparkPi