version: 0.1
component: build
timeoutInSeconds: 20000
runAs: root
shell: bash
env:
  exportedVariables:
   - version
steps:

  - type: Command
    name: "building spark in local"
    command: |
      sudo su
      chmod +x ./build/mvn
      ./build/mvn -DskipTests clean package
#   - type: Command
#     name: "Running tests"
#     command: |
#       ./dev/run-tests
  - type: Command
    name: "run the Pi example locally"
    command: |
      sudo su
      chmod +x -r .
      ./bin/run-example SparkPi      
